### ISSUE TITLE
Project updates - extendedmode?  

### ISSUE THREAD

**Issue by smearieryeti** [S-ESX/sesx-pack#1]
Package hasn't been updated since Dec 2019 on discord;  if this isn't being maintained then why not OS it so we can fork it and maintain it?

**Comment by schwim0341** [comment]
The gnu license is not only included, this pack is nothing more than small changes made to other open source packages. I look forward to your upcoming release.

**Comment by schwim0341** [comment]
Yet to see your fork, figure it's safe to retire this issue.
